version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_URL: mongodb://localhost:27017
      MONGODB_DATABASE: sos
      MONGODB_USER_COLLECTION: sos
      JWT_KEY: dAm0AE50w6hhNP8WUm5bBnnsmegWOcmK
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - sos-service

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
    - sos-service

    restart: always
    volumes:
      - mongodb_data:/var/lib/mongodb/data

volumes:
  mongodb_data:

networks:
  sos-service: